### ISSUE TITLE
CMake build

### ISSUE THREAD

**Issue by v1bri** [quiet/libfec#4]
Not really an issue, but would you guys be interested in adding CMake support to the project? I find it helps with cross compiling. I can submit a pull request if that works.

**Comment by brian-armstrong** [comment]
Well, CMake would definitely make it nicer. It's already arguably broken on osx.

One thing I'd want to see in a CMake impl would be a check for the x86 intrinsics, since libfec can build much faster SSE binaries if those instructions are available.

**Comment by v1bri** [comment]
I think I've got most of that covered. All feedback welcome.

**Comment by brian-armstrong** [comment]
Merged. Thanks again :)

**Comment by sanjeev1994** [comment]
error: fec_get_enc_msg_length(), convolutional codes unavailable (install libfec)

i installed libfec and then also i am getting the above error

**Comment by brian-armstrong** [comment]
@sanjeev1994 I think your error belongs in its own issue, and likely on the quiet project

The next step you'll want to do is re-build/install liquid-dsp. Since you likely built it before having libfec installed, it wouldn't have built is libfec component. Now that you have it, it'll detect it when you rebuild it, and put the libfec handler in to its build. Then you error should go away

**Comment by sanjeev1994** [comment]
Hi Brian Armstrong,
I did the the same thing , I installed remaining dependencies and then only
I built the liquid-dsp. And even now I tired I am getting the same.

Regards
Sanjeev S

**Comment by jgaeddert** [comment]
@sanjeev1994, after installing libfec, you might need to run `sudo ldconfig` to bind the libraries so they can be linked externally.

**Comment by sanjeev1994** [comment]
@jgaeddert I am using mac os. sudo ldconfig is not needed and mac os and that command cant be run in mac os also. If i run that command i am getting this error "sudo: ldconfig: command not found"

**Comment by brian-armstrong** [comment]
@sanjeev1994 Please move this discussion to a new issue. Also, when you do, post any output from liquid's ./configure regarding fec. You should see a couple of lines there regarding either finding or not finding fec.
